### ISSUE TITLE
Connection timeout on some stores with new version

### ISSUE THREAD

**Issue by Tomson124** [jef/streetmerchant#677] opened 2020-11-03 22:05 UTC
### Description

Really weird issue. I am getting connection time outs for media markt, notebooksbilliger and some other stores when I run the new docker container or the the cloned version on my vps. If I run the same version and config on my local machine it works fine. But if I run the older pre 1.6. version as a pm2 instance with just the updated store lists and the same config it works just fine. As far as I understand it is not the IP of the vps being blacklisted as the pm2 instance should be timing out as well then, right?
Really confused right now on whats going on.

### Possible solution
No solution as of right now, not sure if it even is a problem with the software or not.

**Comment by Tomson124** [comment] 2020-11-03 22:14
Should probably also add that pinging the stores that are making problemsis working fine. And there are also some navigation timeouts without a store attached to it. Just tried it again as a simple npm run instead of docker but the same outcome with the newer version: 
![grafik](https://user-images.githubusercontent.com/9150593/98046284-39ac8780-1e2a-11eb-93e7-067a7e729f7a.png)

**Comment by jef** [comment] 2020-11-03 22:23
Whoops, didn't mean to close.

Do you mind sharing your `.env`? I'll run on my end and test.

**Comment by Tomson124** [comment] 2020-11-03 22:46
The .env of the pm2 instance which runs fine.
<details>
<summary>The .env :</summary>

```
# ** All configuration variables are optional **
# Read https://github.com/jef/nvidia-snatcher#customization for help on customizing this file
#############################################################################################

BROWSER_TRUSTED=true
COUNTRY=germany
DESKTOP_NOTIFICATIONS=
DISCORD_NOTIFY_GROUP=
DISCORD_WEB_HOOK=https://discordapp.com/api/webhooks/...
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=false
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=3070
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=nvidia,amazon-de,alternate,mediamarkt,proshop-de,notebooksbilliger,caseking,mindfactory,nvidia-api
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
USER_AGENT=
WEB_PORT=
```
</details>

But if I change some the stores and add 3080 model it also doesnt work anymore in the pm2 instance(pre 1.6.x), could not yet test if it is adding the model or removing amazon-de cause I  have to sleep some now. But really weird issue.
<details>
<summary>The changed .env :</summary>

```
# ** All configuration variables are optional **
# Read https://github.com/jef/nvidia-snatcher#customization for help on customizing this file
#############################################################################################

BROWSER_TRUSTED=true
COUNTRY=germany
DESKTOP_NOTIFICATIONS=
DISCORD_NOTIFY_GROUP=
DISCORD_WEB_HOOK=https://discordapp.com/api/webhooks/...
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=false
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=3070,3080
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=nvidia,alternate,mediamarkt,proshop-de,notebooksbilliger,caseking,mindfactory,nvidia-api
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
USER_AGENT=
WEB_PORT=
```
</details>

**Comment by jef** [comment] 2020-11-03 22:50
Models and pricing were kind of in a weird state with a couple commits that change how models/max price works. I would make sure that you run the latest.

**Comment by jef** [comment] 2020-11-03 22:50
That is a weird issue though.

**Comment by jef** [comment] 2020-11-03 22:51
Perhaps I also misread.

To confirm:

- It's not working on latest via Docker
- It works on pre 1.6.0 via Docker

Correct?

**Comment by AelithBlanchett** [comment] 2020-11-03 23:26
Hi! I'm running 1.7.0.

I was listening to 3070 series only, I added the 3080 and I also get those timeouts now.
I'm listening to bestbuy-ca, amazon-ca and newegg-ca.

`[11:23:58 PM] info :: ℹ selected stores: amazon-ca, bestbuy-ca, newegg-ca
[11:23:58 PM] info :: ℹ selected series: 3070, 3080
[11:23:59 PM] warn :: ✖ couldn't find sound player
[11:24:15 PM] error :: Failed to parse card: PNY GeForce RTX 3070 8GB Dual Fan Ampere Graphics Card
[11:24:39 PM] error :: Navigation timeout of 30000 ms exceeded
[11:24:47 PM] error :: Navigation timeout of 30000 ms exceeded
[11:24:57 PM] error :: ✖ [newegg-ca] asus 3080 tuf - Navigation timeout of 30000 ms exceeded
[11:25:09 PM] error :: ✖ [amazon-ca] msi 3080 gaming x trio - Navigation timeout of 30000 ms exceeded
[11:25:18 PM] error :: Navigation timeout of 30000 ms exceeded
[11:25:23 PM] error :: Navigation timeout of 30000 ms exceeded
[11:25:28 PM] info :: ✖ [bestbuy-ca] [zotac (3080)] trinity :: OUT OF STOCK
[11:25:42 PM] error :: ✖ [amazon-ca] msi 3080 ventus 3x oc - Navigation timeout of 30000 ms exceeded
[11:25:50 PM] error :: Navigation timeout of 30000 ms exceeded
[11:25:55 PM] error :: ✖ [newegg-ca] evga 3080 xc3 black - Navigation timeout of 30000 ms exceeded
[11:26:04 PM] info :: ✖ [bestbuy-ca] [msi (3080)] ventus 3x :: OUT OF STOCK
`

**Comment by jef** [comment] 2020-11-04 00:37
Thanks for the comment @AelithBlanchett. Unfortunately, I can't duplicate the issue :/

```
                    $$\       $$\ $$\                                                  $$\               $$\
                    \__|      $$ |\__|                                                 $$ |              $$ |
$$$$$$$\ $$\    $$\ $$\  $$$$$$$ |$$\  $$$$$$\           $$$$$$$\ $$$$$$$\   $$$$$$\ $$$$$$\    $$$$$$$\ $$$$$$$\   $$$$$$\   $$$$$$\
$$  __$$\\$$\  $$  |$$ |$$  __$$ |$$ | \____$$\ $$$$$$\ $$  _____|$$  __$$\  \____$$\\_$$  _|  $$  _____|$$  __$$\ $$  __$$\ $$  __$$\
$$ |  $$ |\$$\$$  / $$ |$$ /  $$ |$$ | $$$$$$$ |\______|\$$$$$$\  $$ |  $$ | $$$$$$$ | $$ |    $$ /      $$ |  $$ |$$$$$$$$ |$$ |  \__|
$$ |  $$ | \$$$  /  $$ |$$ |  $$ |$$ |$$  __$$ |         \____$$\ $$ |  $$ |$$  __$$ | $$ |$$\ $$ |      $$ |  $$ |$$   ____|$$ |
$$ |  $$ |  \$  /   $$ |\$$$$$$$ |$$ |\$$$$$$$ |        $$$$$$$  |$$ |  $$ |\$$$$$$$ | \$$$$  |\$$$$$$$\ $$ |  $$ |\$$$$$$$\ $$ |
\__|  \__|   \_/    \__| \_______|\__| \_______|        \_______/ \__|  \__| \_______|  \____/  \_______|\__|  \__| \_______|\__|
1.7.0

[7:35:52 PM] info :: ℹ selected stores: bestbuy-ca, amazon-ca, newegg-ca
[7:35:52 PM] info :: ℹ selected series: 3070, 3080
[7:35:57 PM] error :: Failed to parse card: PNY GeForce RTX 3070 8GB Dual Fan Ampere Graphics Card
[7:36:05 PM] info :: ✖ [bestbuy-ca] [zotac (3080)] trinity :: OUT OF STOCK
[7:36:05 PM] info :: ✖ [amazon-ca] [msi (3080)] gaming x trio :: OUT OF STOCK
[7:36:06 PM] info :: ✖ [newegg-ca] [asus (3080)] tuf :: OUT OF STOCK
[7:36:06 PM] info :: ✖ [amazon-ca] [msi (3080)] ventus 3x oc :: OUT OF STOCK
[7:36:07 PM] info :: ✖ [amazon-ca] [evga (3080)] ftw3 :: OUT OF STOCK
[7:36:07 PM] info :: ✖ [bestbuy-ca] [msi (3080)] ventus 3x :: OUT OF STOCK
[7:36:07 PM] info :: ✖ [amazon-ca] [evga (3080)] ftw3 ultra :: OUT OF STOCK
[7:36:08 PM] info :: ✖ [amazon-ca] [evga (3080)] xc3 ultra :: OUT OF STOCK
[7:36:09 PM] info :: ✖ [bestbuy-ca] [evga (3080)] xc3 ultra :: OUT OF STOCK
[7:36:09 PM] info :: ✖ [newegg-ca] [evga (3080)] ftw3 gaming :: OUT OF STOCK
[7:36:09 PM] info :: ✖ [amazon-ca] [evga (3080)] xc3 :: OUT OF STOCK
[7:36:10 PM] info :: ✖ [amazon-ca] [evga (3080)] xc3 black :: OUT OF STOCK
[7:36:11 PM] info :: ✖ [amazon-ca] [gigabyte (3080)] gaming oc :: OUT OF STOCK
[7:36:11 PM] info :: ✖ [bestbuy-ca] [asus (3080)] tuf :: OUT OF STOCK
[7:36:11 PM] info :: ✖ [amazon-ca] [gigabyte (3080)] eagle oc :: OUT OF STOCK
[7:36:12 PM] info :: ✖ [newegg-ca] [evga (3080)] ftw3 ultra :: OUT OF STOCK
[7:36:12 PM] info :: ✖ [amazon-ca] [asus (3080)] tuf :: OUT OF STOCK
^C
```

Are you using `USER_AGENT`? I'd also suggest running `HEADLESS=false` to see what's happening.

**Comment by Tomson124** [comment] 2020-11-04 09:02
> To confirm:
> 
> It's not working on latest via Docker
> It works on pre 1.6.0 via Docker
> Correct?

Sorry was very late yesterday.
Yes it is not working in the latest (nightly) docker with the changed `.env`, I did not try it in pre 1.6 docker as I only have the nightly image (updated via `docker pull`)
The pre 1.6 instance is just a cloned repo with installed dependencies and running `npm run start` but with pm2 so it keeps running and being monitored even after closing the SSH.
Iam currently at work, so no real way of doing further testing, will try when I get home.

**Comment by AelithBlanchett** [comment] 2020-11-04 14:16
I've booted up another beefier droplet on DigitalOcean, reinstalled docker and ran the nightly docker build with the same parameters and it's still timing out at first with the same config, but I eventually get the OOS after a minute or two of failing, instead of nothing at all ever on the less powerful droplet. 
If I remove bestbuy-ca, it immediately pulls the data without any navigation errors.

It's probably just a performance issue maybe?

**Comment by nlflint** [comment] 2020-11-04 18:24
I ran into this today too, after it ran for ~30mins. Ran great for 30mins, then a series of 30s timeout errors on each store shutdown all polling.

**Comment by AelithBlanchett** [comment] 2020-11-04 19:42
I think this _might_ be related to issue #676 
If you look at it, everything starts to fail on the first error from newegg.

**Comment by jef** [comment] 2020-11-04 20:34
I would've guessed at first this:

> I've booted up another beefier droplet on DigitalOcean

If you're using a cloud provider, more than likely, you'll run into issues because of a denylist of IPs.

But I think looking further into this problem is necessary.

**Comment by NGatti1997** [comment] 2020-11-04 21:38
Can second this issue. Works fine on my Windows 10 machine with Powershell, but Ubuntu Server box times out.

**Comment by Tomson124** [comment] 2020-11-04 21:53
So did a little more testing on my side, seems to be the model parameter that messes it up for me. If I only search for 3070s it works fine, but when I am searching for 3080s or both at the same time, it only times times out.
Couldn't be performance, as it is a Intel Xeon Golld (2 dedicated cores), 20GB RAM and RAID 10 SSDs.
IP blacklsit or denylist is highly unlikly (in my case) as searching only for 3070s works and pinging the shops also works just fine.

**Comment by NGatti1997** [comment] 2020-11-04 21:55
I’m having the issue with just the 3070 search so I wonder if it’s an issue
with the brand parameter.

**Comment by treydott** [comment] 2020-11-06 03:21
I am also having this issue. I am running the nightly docker. I tried adjusting the series, models, and page refresh wait times. The issue still seems to occur. I also tried using the normal install, same issue
Timeout starts after a few minutes for me and once a site times out it never tries to refresh the site again.

**Comment by nlflint** [comment] 2020-11-06 22:14
When I run v1.7.0 outside a container (via pulling v1.7.0 tag locally and `npm run start`) then it works fine, no errors.

**Comment by treydott** [comment] 2020-11-07 02:49
I tried it again outside of docker and it appears to be fine as well. Perhaps I was mistaken before. Seems docker specific

**Comment by NGatti1997** [comment] 2020-11-07 04:35
Doesn’t work outside docker for me.

**Comment by jef** [comment] 2020-11-09 06:09
I'm going to run streetmerchant over night with your settings and see if I can reproduce. I'll let you know soon enough! Thank you.

**Comment by jef** [comment] 2020-11-10 14:09
I've been running for a 24 hours with these stores and haven't had any problems. I'm going to close this out due to potentially being client sided. Feel free to open a ticket related to any questions on running the client.

Thanks!

**Closed by jef** 2020-11-10 14:09 UTC
Labels: type: bug

**Comment by reneruiz** [comment] 2020-11-18 23:10
Using docker here, same issue.

**Comment by corvek97** [comment] 2020-11-22 11:54
I stopped getting those after setting the `USER_AGENT=` 

It is also parsing much faster than before after doing that.
