### ISSUE TITLE
Blacklist or ignore product pages?

### ISSUE THREAD

**Issue by grandprixgp** [jef/streetmerchant#959] opened 2020-11-26 18:11 UTC
### Description

For SCAN (UK) I've got a false product repeatedly triggering alerts, [here](https://www.scan.co.uk/products/3m-club-3d-cac-1373-10k-120hz-hdmi-v21-performance-48gb-s-cable-aluminum-hood-black) and it falls under the 3080 category.

Is there a method to blacklist/ignore specific URLs or products?

**Comment by grandprixgp** [comment] 2020-11-26 18:29
After taking a look at the source, it seems this is happening because SCAN lists "related products" at the bottom of the product category, which streetmerchant is parsing as a product. 
![image](https://user-images.githubusercontent.com/10516419/100383279-29489080-3015-11eb-968d-2ffbd221de3c.png)

An easy fix would probably be a minimum value option, but I suppose pushing something specific to ignore this part of SCAN in the scan model would be the best option.

**Comment by louij2** [comment] 2020-11-27 21:12
This is an issue with the link builder picking up on a related item at the bottom of the list.

I fixed this by amending the productsSelector in src/store/model/scan.ts to read
productsSelector: 'div.productList ul.productColumns li.product',
@devon-badman
devon-badman commented 2 days ago

duplicate of #919

**Comment by grandprixgp** [comment] 2020-11-27 22:06
@louij2 Thanks, I've made the change locally so that I can keep using scan. Did you make a PR?

**Comment by jef** [comment] 2020-12-09 07:19
Fixed here https://github.com/jef/streetmerchant/pull/1161

**Closed by jef** 2020-12-09 07:19 UTC
Labels: type: bug
