### ISSUE TITLE
PS5 and Amazon - False hits

### ISSUE THREAD

**Issue by scot-onet** [jef/streetmerchant#775] opened 2020-11-12 13:38 UTC
Getting random false notifications about the ps5 being available.  Looking at the success screenshot, it is showing the dual sense controller and not the ps5 unit itself.  Not a huge deal as it doesn't happen every time it hits amazon, but it is showing up.  

It does not get added to the cart, shows as out of stock on the page it triggers.

**Comment by jef** [comment] 2020-11-12 14:50
Can you provide the screenshot and the link?

**Comment by jmtuna** [comment] 2020-11-12 15:09
Here ya go.  Appears to be related to the way they consolidated the various editions they offer.
https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B08FC5L3RG&Quantity.1=1
![success-1605192326730](https://user-images.githubusercontent.com/74366873/98957307-070c2a00-24cf-11eb-872b-9d588e83e536.png)
](url)

**Comment by jef** [comment] 2020-11-12 15:18
The problem is that the link in the code is pointing to the controller... Not the console. Lol. I will fix. Thanks!

**Comment by jef** [comment] 2020-11-12 15:25
I am not sure what to do as of now. Will keep this open until we do more research.

**Comment by germtuna** [comment] 2020-11-12 19:37
Without some jiggery pokery, the closest I can get is using the EAN as a lookup only but after that they perform their shenanigans. Likely intentional on their side in order to drive requests and notification signups.
Physical:
https://www.amazon.com/s?k=0711719541028&ref=nb_sb_noss
Digital:
https://www.amazon.com/s?k=0711719541035&ref=nb_sb_noss

**Comment by gabriwong** [comment] 2020-11-13 00:07
This may go there directly: https://www.amazon.com/PlayStation-5-Console/dp/B08FC5L3RG

**Comment by jef** [comment] 2020-11-13 03:28
It looks like those links are now directly going to the console/digital edition. Do you mind closing this out if the problem is solved now?

Thanks all!

**Comment by anaisbetts** [comment] 2020-11-19 10:46
This is still hitting for me, it's going to the controller again

**Comment by jef** [comment] 2020-11-21 22:37
Both of these are going to the versions for me.

- https://www.amazon.com/dp/B08FC6MR62
- https://www.amazon.com/dp/B08FC5L3RG

I've also seen where this link will go to the general page with the PS5 on another page. This inconsistency is because of Amazon unfortunately.

**Closed by jef** 2020-11-21 22:37 UTC
Labels: type: bug
