### ISSUE TITLE
Program closes when item is found

### ISSUE THREAD

**Issue by Gieryic** [jef/streetmerchant#2232] opened 2021-03-26 04:18 UTC
## Expected Behavior

Is this intentional - I would expect the program to keep running to find other items. 

## Current Behavior
[dotenv2.txt](https://github.com/jef/streetmerchant/files/6209369/dotenv2.txt)

Command prompt shuts down once item is found and notification sent.

## Environment

- OS:

Windows 10

**Comment by wazerstar** [comment] 2021-03-26 11:16
I noticed the same thing, I believe it hides the command prompt window, as I can see in task manager that chromium task i still running with new instances  all the time.

**Comment by jef** [comment] 2021-03-26 16:25
This seems odd. I don't think I've run into this behavior. I've also not ran on Windows 10. I can try it out in the near future.

**Comment by q-uantum** [comment] 2021-03-27 21:47
I have the same issue

**Comment by kingazar** [comment] 2021-03-28 21:05
I am getting this issue as well, PowerShell or cmd, once he found an item the cmd or PowerShell windows will disappear but still running in the background. Work around for me is to use the GIT BATCH HERE directly.

**Comment by My-Name-Is-Adam** [comment] 2021-03-28 23:29
I am also facing the issue. 

I can confirm the script does continue to run though. 
I am running headles=false. The Chromium browser is still running loading up all of the pages despite the command prompt window disappearing after finding the product.

**Comment by MieszkoT84** [comment] 2021-03-29 01:51
Hi. I also have this issue on 2 separate machines and the only workaround I found is to setup this parameter as 'false':
OPEN_BROWSER=false
I'm relying more on notifications when away from the computer so it's not a big of an issue for me but it needs fixing nevertheless.

**Comment by My-Name-Is-Adam** [comment] 2021-03-30 04:39
> Hi. I also have this issue on 2 separate machines and the only workaround I found is to setup this parameter as 'false':
> OPEN_BROWSER=false
> I'm relying more on notifications when away from the computer so it's not a big of an issue for me but it needs fixing nevertheless.

My guess is this stops the browser opening when a product is found? This would be a dealbreaker for me. That feature is too valuable to disable.

**Comment by MieszkoT84** [comment] 2021-03-30 11:21
> > Hi. I also have this issue on 2 separate machines and the only workaround I found is to setup this parameter as 'false':
> > OPEN_BROWSER=false
> > I'm relying more on notifications when away from the computer so it's not a big of an issue for me but it needs fixing nevertheless.
> 
> My guess is this stops the browser opening when a product is found? This would be a dealbreaker for me. That feature is too valuable to disable.

Yes, that's what it does but I'm using mine on VM for notification purpose only and buying on a phone or other machines so it's not a problem for me but may be for others. Tried practically everything but ran out of ideas so left it at that until it's fixed.

**Comment by ordinafdim** [comment] 2021-03-30 14:46
Also having the same issue and never had it in the past.

**Comment by timuriss** [comment] 2021-04-02 01:36
I have the same problem. CMD is minimizing into nothingness.

**Comment by Putrefactium** [comment] 2021-04-08 00:20
Same for me here, it does disappear but still running in background

Windows 10

**Comment by Ben-JHenry** [comment] 2021-04-10 23:56
Same here. Frustrating because I keep getting false positives, which leads to the cmd window closing and then I can't see the status of CAPTCHAS, errors, etc. anymore

**Comment by r-bman** [comment] 2021-04-25 13:23
This is happening for me on Windows and I can confirm that setting `OPEN_BROWSER=false` solves the problem, which is acceptable for me but this still needs a fix. I tried to figure out what's going on but I got a bit lost in the code.

**Closed** 2021-04-29 14:30 UTC
Labels: priority: normal, status: help wanted, status: needs triage
