### ISSUE TITLE
Playstation store not working

### ISSUE THREAD

**Issue by TheTabKey** [jef/streetmerchant#809] opened 2020-11-15 18:56 UTC
Just doesnt seem to want to search the playstation store, and cant seem to find out why.
![fBvtoEu](https://user-images.githubusercontent.com/26450925/99193999-7719ea80-2731-11eb-86b3-6567f4ae8b39.png)

searches every other store for ps5

edit: looks like playstation.ts needs to be updated

**Comment by kyleroath** [comment] 2020-11-15 19:24
I believe the issue is that an out of stock label was not created for the Playstation Store. I've yet to look at the code or API myself, just going off what's found in J-Hinton's merge. Meaning it would never display an out of stock message yet, only when in stock... if I am not mistaken?

**Comment by noblesin** [comment] 2020-11-15 19:37
That is correct - The Playstation Store works but only shows up when It is IN STOCK. There is no check for Out of Stock. J-Hinton mentioned that in his merge. This is not a bug.

**Comment by kyleroath** [comment] 2020-11-15 19:53
> That is correct - The Playstation Store works but only shows up when It is IN STOCK. There is no check for Out of Stock. J-Hinton mentioned that in his merge. This is not a bug.

Got it! Just checked the code too, I see what he's saying. I'll be taking a look tonight to see if I can aid in creating the OOS label too. Hopefully you guys beat me to it 👍

**Comment by J-Hinton** [comment] 2020-11-15 21:14
The issue we have is that both *Add* and the *Out of stock* message is within the HTML selector. Once the API call has been returned, the appropriate message is only hidden.  

Within the [lookupCardInStock](https://github.com/jef/streetmerchant/blob/32702929a97236d7dc51aa8f669140bc6d89aa9a/src/store/lookup.ts#L153) function, there are options for the inStock label where `requireVisible: true` meaning it will select whatever is visible on the screen. If we can do the same for the outOfStock label, then we shouldn't have an issue - Not sure if there are any dependencies in other stores for this to be set to false.

In the event of the item being available, it uses API to validate. Should the API return saying the item is out of stock, then I believe there is no message saying OutOfStock... if the API confirms it's in-stock, the normal workflow will occur.

**Comment by J-Hinton** [comment] 2020-11-15 21:37
Update on this topic: I now have a working version to implement the OUT OF STOCK message. 

Just submitting a PR to close this issue. 

![image](https://user-images.githubusercontent.com/65028523/99197396-2da9b980-278a-11eb-8f23-0c7d23ec80ed.png)

**Comment by noblesin** [comment] 2020-11-15 21:40
Wonderful - Thank you @J-Hinton for working on this .. Much appreciated!

**Closed** 2020-11-15 22:45 UTC
Labels: type: bug

**Comment by jef** [comment] 2020-11-16 16:21
@thanks @J-Hinton !

**Comment by huntinganswers** [comment] 2020-11-28 12:03
I finally have this slick script to run, but now I get zero responses searching for consoles.
![example](https://user-images.githubusercontent.com/75166450/100515148-788ae000-313f-11eb-9f8b-7a2c18f333ff.JPG)

**Comment by huntinganswers** [comment] 2020-11-28 12:06
I can't seem to get any response from the merchants with consoles...
![example](https://user-images.githubusercontent.com/75166450/100515195-ca336a80-313f-11eb-804c-9c9495f39495.JPG)
